[tool.pytest]
pythonpath = "."
testpaths = ["tests"]

[tool.ruff]
exclude = ["*.ipynb", "tests/", "scripts/", "utils/", "migrations/", "app_old/"]
line-length = 120

[tool.ruff.lint]
select = ["E", "W", "F", "I", "N", "UP", "B", "SIM", "TCH"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space" 
skip-magic-trailing-comma = false
line-ending = "auto"