name: 🎯 Run Unit Test via Pytest  
  
on: [push]
  
jobs:  
  build:  
    runs-on: ubuntu-latest  

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: zmitac_test
        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:  
      matrix:  
        python-version: ["3.10", "3.11", "3.12"]
      include:
        - python-version: "3.13"
          experimental: true
      allow-failure:
        - python-version: "3.13"  
  
    steps:
      - uses: actions/checkout@v3  

      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}  

      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  

      - name: Lint with Ruff
        run: |
          ruff check app/
      
      - name: Format with Ruff
        run: |
          ruff format --check app/

      - name: Test with pytest  
        run: |  
          pytest --cov --junitxml=junit.xml -o junit_family=legacy
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/zmitac_test

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
